name: parse-recipe
version: 0.1.0.0
synopsis: Parsing markdown recipes
description: Please see the README at <https://github.com/jwoudenberg/groceries/tree/trunk/parse-recipe>.
author: Jasper Woudenberg
maintainer: mail@jasperwoudenberg.com
copyright: 2021 Jasper Woudenberg
license-file: LICENSE
category: Web
github: jwoudenberg/groceries
extra-doc-files:
- README.md
library:
  exposed-modules:
  - ParseRecipe
  source-dirs: src
executables:
  parse-recipe:
    dependencies:
    - parse-recipe
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts "-with-rtsopts=-N -T"
    - -O2
dependencies:
- attoparsec >= 0.13.0.0 && < 0.15
- base >= 4.10.1.0 && < 5
- containers >= 0.6.5.1 && < 0.7
- directory >= 1.3.3.0 && < 1.4
- text >= 1.2.3.0 && < 2.1
- pandoc >= 2.14 && < 2.17
ghc-options:
- -Wall
- -Werror
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wpartial-fields
- -Wredundant-constraints
- -Wincomplete-uni-patterns
default-extensions:
- DeriveGeneric
- GeneralizedNewtypeDeriving
- NamedFieldPuns
- NumericUnderscores
- OverloadedStrings
- ScopedTypeVariables
- StrictData
