[project]
name = "cooklang"
version = "1.0.0"
authors = [
  { name="Jasper Woudenberg", email="mail@jasperwoudenberg.com" },
]
description = "A cooklang parser and html renderer"
readme = "README.md"
requires-python = ">=3.8"

[project.scripts]
cooklang = "cooklang.cli:main"
