#!/usr/bin/env bash

set -euo pipefail

# This takes an existing grocery list on stdin and a recipe as arguments, then
# returns an updated grocery list on stdout
#
# This allows testing grocery-list updates using shelltest
RECIPE="$*"
FILE=$(mktemp)
cat > "$FILE"
echo "$RECIPE" | PYTHONPATH=src/ src/cooklang/cli.py --output "$FILE"
cat "$FILE"
