#!/usr/bin/env python3

import sys
import cooklang
import recipe_html


def main():
    recipeText = sys.stdin.buffer.read()
    recipe = cooklang.parseRecipe(recipeText)
    html = recipe_html.toHtml(recipe.asDict())
    sys.stdout.buffer.write(html)


if __name__ == "__main__":
    main()
